- hosts: localhost
  tasks:
    - name: Create a network
      openstack.cloud.network:
        cloud: "{{ cloud }}"
        state: present
        name: "{{ net_name }}"

    - name: Create an IPv6 subnet
      openstack.cloud.subnet:
        state: present
        name: "{{ subnet_name }}"
        network_name: "{{ net_name }}"
        ip_version: '6'
        cidr: 2001:db8:2222:5555::/64
        ipv6_ra_mode: 'slaac'
        ipv6_address_mode: 'slaac'

    - name: Create new instances connected to "{{ net_name }}" network
      openstack.cloud.server:
        state: present
        cloud: "{{ cloud }}"
        name: "{{ item }}"
        image: "{{ image_name }}"
    #       key_name: ansible_key
        timeout: 200
        flavor: "{{ flavor_name }}"
        nics:
          - net-name: "{{ net_name }}"
      loop: "{{ vms_names }}"
