- hosts: localhost
  tasks:
    - include_role:
        name: ipv6
        tasks_from: create_server.yml
      tags: create

    - include_role:
        name: ipv6
        tasks_from: clean_server.yml
      tags: clean
    
