- hosts: localhost
  tasks:
    - include_role:
        name: ipv6
        tasks_from: create_server.yml
      when: create

    - include_role:
        name: ipv6
        tasks_from: clean_server.yml
      when: clean

    
